### PR TITLE
Modifier should be set separately on base and extended blocks

### PR DESCRIPTION
**Pull request by zxqfox**
Original task: https://nda.ya.ru/3TTfpA

Example:
```js
const A = decl({ block : 'a' });;
const Amod = declMod({ mod : true }, { block : 'a' });

const AComponent = applyDecls(A, Amod);

const B = decl(AComponent, { block : 'b' });
const Bmod = declMod({ mod : true }, { block : 'b' });

const BComponent = applyDecls(B, Bmod);

const jsx = <BComponent mod>;
// <div class="a b b_mod"></div>
```

Also would be nice to have a way to pass mod to any of base blocks (`AComponent` in example).

### CODE REVIEW

**Comment by Yeti-or** [comment]
@zxqfox you expected 
```
const jsx = <BComponent mod>;
// <div class="a a_mod b b_mod"></div> 
```
?

**Comment by zxqfox** [comment]
No, I even said "separately" ;-) This means it would NOT expect `base_mod` (`a_mod`) but I'm not sure how this works in bem-react-core so I want a spec/test for this case.

p.s. This issue about a test.

p.p.s. Why you using fixtures like these? You sure you need to build components in each test with `bem-loader`, `bem-import-notation`, `webpack`, etc.
I'd wish to see declarations and applyDecls inlined (something like I wrote it in this issue).

**Comment by awinogradov** [comment]
@zxqfox we added the spec for expectable behavior and it's green. It' what did you expect?

**Comment by zxqfox** [comment]
Nice!

The main problem for me is losing css for extended blocks, and especially for their mixes.

For now we must extend manually `addMix` in extended class and extended modifier to add needed classes for browser.

**Comment by awinogradov** [comment]
Yes, I understand your problem. So, we don't have a decision in this case. But I think this problem connected to https://github.com/bem/bem-react-core/issues/16 and we need to make a complex decision.

**Comment by awinogradov** [comment]
Lets do it here #158

**Pull request closed without merging**
